### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by Alexikon** [rstropek/htl-csharp#68]
Dear Mr. Stropek,
here is the link to my Resistor-Colors-Exercise project (with the visual representations on both tabs)
https://github.com/Alexikon/resistor-color-exercise-alexikon
Sincerely
Alex Tischlinger

**Comment by rstropek** [comment]
Very well done (also great job during this week's lesson 💪). The extra points are yours.

Greetings,
Rainer Stropek.
